name: pogos_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  dio: ^5.3.3
  retrofit: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: '>=7.0.0 <8.0.0'
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  build_test: ^2.2.0

flutter:
  generate: true
  uses-material-design: true
